### ISSUE TITLE
Cannot toggle on "Allow media management" under privacy settings

### ISSUE THREAD

**Issue by matdam99** [deckerst/aves#1036]
[**Describe](url) the bug**
Every time I try to toggle on the allow media management toggle under privacy settings, the app crashes.  

**To Reproduce**
1. Go to settings in top left
2. Click on privacy menu
3. Try to toggle on "allow media management"
4. See error - app crashes

**Expected behavior**
the toggle should turn on and the app should not ask me to confirm everytime I want to delete a file. 

**Screenshots**

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.11.1-play, build 120
Flutter: stable 3.19.6
Android version: 12, API 31
Android build: SKQ1.211103.001
Device: LGE LM-G850
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: en_AU, en_US
Storage volumes: /storage/emulated/0/, /storage/3962-6638/
Storage grants: /storage/emulated/0/Pictures/
Error reporting: false

Log:
--------- beginning of main
06-01 18:38:31.957  3311  3311 E s.thibault.ave: Not starting debugger since process cannot load the jdwp agent.
06-01 18:38:31.961  3311  3311 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-01 18:38:31.991  3311  3311 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10369; state: ENABLED
06-01 18:38:31.993  3311  3311 I Typeface: HYFONTS.setDefault.OK:0, default_lgsmartui
06-01 18:38:32.033  3311  3311 W s.thibault.ave: Entry not found
06-01 18:38:32.036  3311  3311 W s.thibault.ave: Entry not found
06-01 18:38:32.037  3311  3311 W s.thibault.ave: Entry not found
06-01 18:38:32.046  3311  3311 W s.thibault.ave: JIT profile information will not be recorded: profile file does not exist.
06-01 18:38:32.046  3311  3311 W s.thibault.ave: JIT profile information will not be recorded: profile file does not exist.
06-01 18:38:32.046  3311  3311 W s.thibault.ave: JIT profile information will not be recorded: profile file does not exist.
06-01 18:38:32.055  3311  3311 V GraphicsEnvironment: ANGLE Developer option for 'deckers.thibault.aves' set to: 'default'
06-01 18:38:32.055  3311  3311 V GraphicsEnvironment: Updatable production driver is not supported on the device.
06-01 18:38:32.056  3311  3311 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-01 18:38:32.056  3311  3311 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-01 18:38:32.062  3311  3311 I MultiDex: VM with version 2.1.0 has multidex support
06-01 18:38:32.062  3311  3311 I MultiDex: Installing application
06-01 18:38:32.062  3311  3311 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-01 18:38:32.083  3311  3311 D SessionsDependencies: Dependency to CRASHLYTICS added.
06-01 18:38:32.085  3311  3311 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
06-01 18:38:32.113  3311  3311 D FirebaseSessions: Initializing Firebase Sessions SDK.
06-01 18:38:32.114  3311  3311 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.6.3 for deckers.thibault.aves
06-01 18:38:32.135  3311  3311 D SessionsDependencies: Subscriber CRASHLYTICS registered.
06-01 18:38:32.136  3311  3333 D FirebaseSessions: No Sessions subscribers. Not listening to lifecycle events.
06-01 18:38:32.163  3311  3311 I FirebaseInitProvider: FirebaseApp initialization successful
06-01 18:38:32.168  3311  3311 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
06-01 18:38:32.172  3311  3311 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
06-01 18:38:32.172  3311  3311 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
06-01 18:38:32.193  3311  3311 I d.t.a.MainActivity: onCreate intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=deckers.thibault.aves/.MainActivity bnds=[852,286][1025,578] }
06-01 18:38:32.194  3311  3340 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10369; state: ENABLED
06-01 18:38:32.203  3311  3334 I FirebaseCrashlytics: Saved version control info
06-01 18:38:32.209  3311  3311 I d.t.a.MainActivity: onStart
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: QUALCOMM build                   : 820d4a4028, I5580630f49
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Build Date                       : 11/04/21
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Local Branch                     : mybranchec3d3d48-61ef-f189-91a8-ac1f6bcc2cee
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Remote Branch                    : NONE
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
06-01 18:38:32.276  3311  3311 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-01 18:38:32.280  3311  3311 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
06-01 18:38:32.313  3311  3311 D ffmpeg-kit-flutter: FFmpegKitFlutterPlugin created n1.k@6c1d396.
06-01 18:38:32.313  3311  3311 D ffmpeg-kit-flutter: FFmpegKitFlutterPlugin n1.k@6c1d396 attached to engine.
06-01 18:38:32.314  3311  3311 I ffmpeg-kit: Loading ffmpeg-kit.
06-01 18:38:32.348  3311  3356 D ffmpeg-kit: Async callback block started.
06-01 18:38:32.350  3311  3311 I ffmpeg-kit: Loaded ffmpeg-kit-video-arm64-v8a-6.0-lts-20230913.
06-01 18:38:32.351  3311  3311 D ffmpeg-kit-flutter: FFmpegKitFlutterPlugin n1.k@6c1d396 initialised with context androidx.multidex.MultiDexApplication@3901b04.
06-01 18:38:32.351  3311  3311 D ffmpeg-kit-flutter: FFmpegKitFlutterPlugin n1.k@6c1d396 attached to activity deckers.thibault.aves.MainActivity@5aee8ed.
06-01 18:38:32.351  3311  3311 D ffmpeg-kit-flutter: FFmpegKitFlutterPlugin n1.k@6c1d396 initialised with activity deckers.thibault.aves.MainActivity@5aee8ed.
06-01 18:38:32.366  3311  3311 I media_kit: package:media_kit_libs_android_video attached.
06-01 18:38:32.370  3311  3311 D media_kit: lge
06-01 18:38:32.383  3311  3311 D media_kit: mh2lm
06-01 18:38:32.383  3311  3311 D media_kit: lge/mh2lm/mh2lm:12/SKQ1.211103.001/2301022043708.OPEN_ESA_DS:user/release-keys
06-01 18:38:32.383  3311  3311 D media_kit: mh2lm
06-01 18:38:32.383  3311  3311 D media_kit: LM-G850
06-01 18:38:32.383  3311  3311 D media_kit: LGE
06-01 18:38:32.383  3311  3311 D media_kit: mh2lm
06-01 18:38:32.384  3311  3311 I media_kit: Saved application context.
06-01 18:38:32.417  3311  3311 I H.t     : start listening to Media Store
06-01 18:38:32.422  3311  3311 I H.y     : start listening to system settings
06-01 18:38:32.459  3311  3329 I d.t.a.MainActivity: set shortcuts: videos, search, safeMode
06-01 18:38:32.515  3311  3311 D DecorView: [DecorView][notifyViewAdded] token = android.view.ViewRootImpl$WEx@adf1c24
06-01 18:38:32.525  3311  3311 I TouchFilterInputStageHelper: [needTouchEventFilter] Displayid : 0
06-01 18:38:32.528  3311  3311 D HandGripFilter: getdisplaysize, x : 1080 y : 2340
06-01 18:38:32.562  3311  3348 I flutter : Report log=Lifecycle resumed
06-01 18:38:32.562  3311  3348 I flutter : failed to get Firebase Crashlytics instance with error=[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
06-01 18:38:32.562  3311  3348 I flutter : #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193)
06-01 18:38:32.562  3311  3348 I flutter : #1      Firebase.app (package:firebase_core/src/firebase.dart:56)
06-01 18:38:32.562  3311  3348 I flutter : #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:33)
06-01 18:38:32.562  3311  3348 I flutter : #3      PlatformReportService._instance (package:aves_report_platform/aves_report_platform.dart:14)
06-01 18:38:32.562  3311  3348 I flutter : #4      PlatformReportService.log (package:aves_report_platform/aves_report_platform.dart:58)
06-01 18:38:32.562  3311  3348 I flutter : #5      _AvesAppState.didChangeAppLifecycleState (package:aves/widgets/aves_app.dart:375)
06-01 18:38:32.562  3311  3348 I flutter : #6      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:799)
06-01 18:38:32.562  3311  3348 I flutter : #7      List.forEach (dart:core-patch/growable_array.dart:416)
06-01 18:38:32.562  3311  3348 I flutter : #8      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:284)
06-01 18:38:32.562  3311  3348 I flutter : #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235)
06-01 18:38:32.562  3311  3348 I flutter : #10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603)
06-01 18:38:32.562  3311  3348 I flutter : #11     _invoke2 (dart:ui/hooks.dart:344)
06-01 18:38:32.562  3311  3348 I flutter : #12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
06-01 18:38:32.562  3311  3348 I flutter : #13     _Channel.push (dart:ui/channel_buffers.dart:135)
06-01 18:38:32.562  3311  3348 I flutter : #14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
06-01 18:38:32.562  3311  3348 I flutter : #15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737)
06-01 18:38:32.562  3311  3348 I flutter : #16     _dispatchPlatformMessage (dart:ui/hooks.dart:257)
06-01 18:38:32.562  3311  3348 I flutter : 
06-01 18:38:32.569  3311  3349 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-01 18:38:32.734  3311  3348 I flutter : dynamic_color: Core palette detected.
06-01 18:38:32.760  3311  3311 D ViewRootImpl[MainActivity]: RTAnimations enable
06-01 18:38:32.760  3311  3348 I flutter : Device is connected=true
06-01 18:38:32.792  3311  3348 I flutter : Device has Google Play Services=true
06-01 18:38:32.812  3311  3348 I flutter : App setup in 329ms
06-01 18:38:32.816  3311  3348 I flutter : Apply display refresh rate: auto
06-01 18:38:32.826  3311  3348 I flutter : disable Firebase & Crashlytics collection
06-01 18:38:32.827  3311  3311 D permissions_handler: No permissions found in manifest for: []9
06-01 18:38:32.827  3311  3311 D permissions_handler: No permissions found in manifest for: []32
06-01 18:38:32.842  3311  3348 I flutter : Access installed app inventory
06-01 18:38:32.842  3311  3348 I flutter : Report log=Intent data={safeMode: false, launcher: true}
06-01 18:38:32.843  3311  3348 I flutter : Storage check complete in 29ms
06-01 18:38:32.845  3311  3348 I flutter : Report log=Launch
06-01 18:38:32.863  3311  3348 I flutter : MediaStoreSource load essentials complete in 19ms
06-01 18:38:32.865  3311  3348 I flutter : MediaStoreSource refresh start
06-01 18:38:32.865  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.000082 load 98 top entries
06-01 18:38:32.865  3311  3348 I flutter : Report log=Nav push to /collection
06-01 18:38:32.866  3311  3348 I flutter : Report log=Nav remove to unnamed null
06-01 18:38:32.900  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.035312 fetch known entries
06-01 18:38:33.053  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.188118 check obsolete entries
06-01 18:38:33.129  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.264164 add known entries
06-01 18:38:33.144  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.278561 load metadata
06-01 18:38:33.175  3311  3348 I flutter : Evict cached images for uri=content://media/external/images/media/74, mimeType=image/png, dateModifiedSecs=1658196391, rotationDegrees=0, isFlipped=false
06-01 18:38:33.176  3311  3348 I flutter : Evict cached images for uri=content://media/external/images/media/93, mimeType=image/png, dateModifiedSecs=1607484112, rotationDegrees=0, isFlipped=false
06-01 18:38:33.244  3311  3348 I flutter : MediaStoreSource refresh 0:00:00.378918 check obsolete paths
06-01 18:38:33.283  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230041.png
06-01 18:38:33.292  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230038.png
06-01 18:38:33.293  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230028.png
06-01 18:38:33.293  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230023.png
06-01 18:38:33.293  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230020.png
06-01 18:38:33.294  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230006.png
06-01 18:38:33.294  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-230001.png
06-01 18:38:33.294  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225952.png
06-01 18:38:33.295  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225949.png
06-01 18:38:33.295  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225946.png
06-01 18:38:33.295  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225942.png
06-01 18:38:33.295  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225933.png
06-01 18:38:33.295  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225925.png
06-01 18:38:33.296  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-225918.png
06-01 18:38:33.296  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-065729.png
06-01 18:38:33.297  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-065708.png
06-01 18:38:33.299  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-065657.png
06-01 18:38:33.300  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-065617.png
06-01 18:38:33.300  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-065602.png
06-01 18:38:33.300  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-064916.png
06-01 18:38:33.300  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-064146.png
06-01 18:38:33.303  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-064056.png
06-01 18:38:33.303  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063932.png
06-01 18:38:33.303  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063816.png
06-01 18:38:33.303  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063804.png
06-01 18:38:33.304  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063800.png
06-01 18:38:33.304  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063741.png
06-01 18:38:33.304  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063734.png
06-01 18:38:33.304  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063720.png
06-01 18:38:33.305  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063711.png
06-01 18:38:33.305  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063522.png
06-01 18:38:33.305  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063518.png
06-01 18:38:33.305  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240126-063512.png
06-01 18:38:33.308  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20230512-113230.png
06-01 18:38:33.312  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240220-061137.png
06-01 18:38:33.312  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240323-063402.png
06-01 18:38:33.313  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240321-164826.png
06-01 18:38:33.314  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240319-185527.png
06-01 18:38:33.315  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240319-184343.png
06-01 18:38:33.315  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240319-182409.png
06-01 18:38:33.316  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240309-141315.png
06-01 18:38:33.317  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240309-131134.png
06-01 18:38:33.319  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240309-131004.png
06-01 18:38:33.320  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-072115.png
06-01 18:38:33.321  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-072050.png
06-01 18:38:33.321  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071959.png
06-01 18:38:33.321  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071940.png
06-01 18:38:33.322  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071933.png
06-01 18:38:33.323  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071856.png
06-01 18:38:33.323  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071844.png
06-01 18:38:33.323  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071832.png
06-01 18:38:33.324  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071814.png
06-01 18:38:33.324  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/data/deckers.thibault.aves/files/trash/Screenshot_20240308-071803.png
06-01 18:38:33.325  3311  3389 D O.r     : delete file at path=/storage/emulated/0/Android/d

**Additional context**
I have two phones, one on android 12 and 14. I know this setting was previously toggled "on" on both devices, but now the app keeps crashing when I try to toggle this option. 

[aves-logs-20240601_183912.txt](https://github.com/user-attachments/files/15521157/aves-logs-20240601_183912.txt)

**Comment by deckerst** [comment]
Related:
- #925

In that other issue, I had blamed Samsung's One UI, but obviously I was wrong.

> I have two phones, one on android 12 and 14. I know this setting was previously toggled "on" on both devices, but now the app keeps crashing when I try to toggle this option.

This setting can be toggled directly via the Android app settings too. Do you remember toggling it via Aves itself? If it was working then and now it crashes, would you pinpoint any change, like an OS upgrade, Aves upgrade, or something else?

Do you know your way around `logcat`?

Do you use a custom ROM?

**Comment by deckerst** [comment]
Also, I see on [gsmarena](https://www.gsmarena.com/lg_g8_thinq-9540.php) that your device is not supposed to have Android 12. Did you get it on your device by official OTA update, or another way?
