### ISSUE TITLE
Scan crash / Memory? / Crash during media analysis

### ISSUE THREAD

**Issue by Toby7-7** [deckerst/aves#782]
**Describe the bug**
This app will crash after about 30 seconds every time it is started.  The only thing the app is doing is in the screenshot below.

**To Reproduce**
Nothing, just start the app

**Expected behavior**
Crashed

**Screenshots**
![Screenshot_2023-10-04-15-15-27-89_ee4e2c77f5dd6d2](https://github.com/deckerst/aves/assets/57825408/b6acac6a-894f-417b-89b7-27e455768be2)

**System information and logs:**
log: 2023-10-04 15:07:06.274 21330-21363 AndroidRuntime          deckers.thibault.aves                E  FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: deckers.thibault.aves, PID: 21330
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 36920416 byte allocation with 25165824 free bytes and 24MB until OOM, target footprint 401883016, growth limit 402653184
                                                                                                    	at java.util.Arrays.copyOf(Arrays.java:3136)
                                                                                                    	at java.util.Arrays.copyOf(Arrays.java:3106)
                                                                                                    	at java.util.ArrayList.grow(ArrayList.java:275)
                                                                                                    	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
                                                                                                    	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
                                                                                                    	at java.util.ArrayList.add(ArrayList.java:467)
                                                                                                    	at org.mp4parser.BasicContainer.initContainer(Unknown Source:32)
                                                                                                    	at org.mp4parser.IsoFile.<init>(Unknown Source:7)
                                                                                                    	at da.a0.c(Unknown Source:60)
                                                                                                    	at y9.g0.y(Unknown Source:1748)
                                                                                                    	at y9.g0.x(Unknown Source:70)
                                                                                                    	at y9.g0.d(Unknown Source:0)
                                                                                                    	at y9.g0$b1$a.e(Unknown Source:14)
                                                                                                    	at y9.g0$b1$a.invoke(Unknown Source:4)
                                                                                                    	at y9.h$a.a(Unknown Source:20)
                                                                                                    	at y9.g0$b1.invokeSuspend(Unknown Source:23)
                                                                                                    	at ub.a.resumeWith(Unknown Source:11)
                                                                                                    	at lc.v0.run(Unknown Source:93)
                                                                                                    	at qc.o$a.run(Unknown Source:3)
                                                                                                    	at sc.k.run(Unknown Source:2)
                                                                                                    	at sc.a.H(Unknown Source:0)
                                                                                                    	at sc.a$c.d(Unknown Source:14)
                                                                                                    	at sc.a$c.p(Unknown Source:28)
                                                                                                    	at sc.a$c.run(Unknown Source:0)
                                                                                                    	Suppressed: qc.i: [k2{Cancelling}@5c1ee29, Dispatchers.IO]

device information: OPPO Find X2 Pro
![Screenshot_2023-10-04-15-19-59-88_1b0813e039defa1](https://github.com/deckerst/aves/assets/57825408/87d6dd10-9bce-4f99-a635-d4a4988b2458)
![Screenshot_2023-10-04-15-21-07-26](https://github.com/deckerst/aves/assets/57825408/45597a5d-9660-4a08-a958-05bf87318b95)

**Comment by deckerst** [comment]
One of your videos is making Aves crash. It will be helpful if we can identify this video in your collection.

Please do the following:
1) start the app via the "Safe mode" shortcut. This will disable the analysis and should prevent the crash, so you can do the next steps.
2) Go to `About` > `Bug Report`, and attach here the system environment and logs you get.
3) In `Settings` > `Privacy`, enable `Allow anonymous error reporting` (if it's not already the case). Then relaunch the app normally to make it crash a couple of times. Hopefully I can see the reports online for these crashes.

**Comment by Toby7-7** [comment]
[aves-logs-20231005_135916.txt](https://github.com/deckerst/aves/files/12812821/aves-logs-20231005_135916.txt)
Allow anonymous error reporting now is enabled and here is the log.

**Comment by deckerst** [comment]
If you open the following file by opening it in Aves from another app (a file browser or another gallery):
`/storage/emulated/0/DCIM/Camera/VID20210521153629.mp4`
Does it crash? If so, would you be willing to share it with me? (link by email also possible)

> Unfortunately it will still crash even in safe mode.

In safe mode, does it still crash from the background, or is it when you browse to some video? The crash happens because the video analysis, which can be triggered lazily in the background, but also eagerly when accessing a video. The safe mode only disables the background analysis.

**Comment by Toby7-7** [comment]
I've sent the video via email.
This video will not cause crashes in other apps.
aves will crash when the scanning progress in the notification bar reaches 266, it will stop and then crash.

**Comment by deckerst** [comment]
@Toby7-7 Does it still crash with the latest version of Aves?

If so, could you try [this](https://github.com/deckerst/aves/issues/977#issuecomment-2061905514)?
